# Generated by Django 5.1.1 on 2024-09-30 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('image', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('tel', models.BigIntegerField(blank=True, null=True)),
                ('postcode', models.CharField(max_length=20)),
                ('ServeYouWant', models.TextField()),
            ],
        ),
    ]
