# Generated by Django 5.1.1 on 2024-10-06 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_remove_service_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='location',
        ),
    ]
