# Generated by Django 5.1.1 on 2024-09-30 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('price', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=255)),
                ('kilometers', models.IntegerField()),
                ('fuelType', models.CharField(max_length=50)),
                ('transmission', models.CharField(max_length=50)),
                ('bodyType', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('engineCapacity', models.IntegerField()),
                ('registeredIn', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='UsedCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('price', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=255)),
                ('kilometers', models.IntegerField()),
                ('fuelType', models.CharField(max_length=50)),
                ('transmission', models.CharField(max_length=50)),
                ('bodyType', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('engineCapacity', models.IntegerField()),
                ('registeredIn', models.CharField(max_length=4)),
            ],
        ),
    ]
