# Generated by Django 5.1.1 on 2024-10-04 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_newcar_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='usedcar',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
