# Generated by Django 5.1.1 on 2024-09-30 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=15)),
                ('payment_method', models.CharField(choices=[('debit_card', 'Debit Card'), ('credit_card', 'Credit Card')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('car_type', models.CharField(blank=True, max_length=10, null=True)),
                ('car_id', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
